-- Auto-generated from zapper/ddl_postgres.sql (PK/FK) + zapper_business_seed.sql (value profiling)
-- Target: ce_mcp_schema_knowledge with valid_values support

ALTER TABLE IF EXISTS ce_mcp_schema_knowledge
  ADD COLUMN IF NOT EXISTS valid_values VARCHAR(2000);

INSERT INTO ce_mcp_schema_knowledge (id, table_name, column_name, valid_values, description, tags)
VALUES
  (21001, 'zp_account', NULL, NULL, 'Entity table zp_account used in Zapper business workflow.', 'account,table,entity'),
  (21002, 'zp_account', 'account_id', NULL, 'Primary key for zp_account.', 'account,id,pk,identifier'),
  (21003, 'zp_account', 'account_status', 'ACTIVE', 'Business attribute in zp_account. Valid values include: ACTIVE.', 'account,status,column,enum'),
  (21004, 'zp_account', 'bill_plan_code', 'BIZ-FLEX,IND-GRID,SMB-SAVER', 'Business attribute in zp_account. Valid values include: BIZ-FLEX,IND-GRID,SMB-SAVER.', 'account,bill,plan,code,column,enum'),
  (21005, 'zp_account', 'created_at', NULL, 'Business attribute in zp_account.', 'account,created,at,column,time'),
  (21006, 'zp_account', 'current_billing_cost', NULL, 'Business attribute in zp_account.', 'account,current,billing,cost,column'),
  (21007, 'zp_account', 'customer_id', NULL, 'Foreign key in zp_account; joins to zp_customer.customer_id.', 'account,customer,id,fk,identifier'),
  (21008, 'zp_account', 'provider_code', 'ZAPPER', 'Business attribute in zp_account. Valid values include: ZAPPER.', 'account,provider,code,column,enum,identifier'),
  (21009, 'zp_account', 'updated_at', NULL, 'Business attribute in zp_account.', 'account,updated,at,column,time'),
  (21010, 'zp_account_location', NULL, NULL, 'Entity table zp_account_location used in Zapper business workflow.', 'account,location,table,entity'),
  (21011, 'zp_account_location', 'acc_loc_id', NULL, 'Primary key for zp_account_location.', 'account,location,acc,loc,id,pk,identifier'),
  (21012, 'zp_account_location', 'account_id', NULL, 'Foreign key in zp_account_location; joins to zp_account.account_id.', 'account,location,id,fk,identifier'),
  (21013, 'zp_account_location', 'created_at', NULL, 'Business attribute in zp_account_location.', 'account,location,created,at,column,time'),
  (21014, 'zp_account_location', 'customer_id', NULL, 'Foreign key in zp_account_location; joins to zp_customer.customer_id.', 'account,location,customer,id,fk,identifier'),
  (21015, 'zp_account_location', 'customer_loc_id', NULL, 'Business attribute in zp_account_location.', 'account,location,customer,loc,id,column,identifier'),
  (21016, 'zp_account_location', 'location_id', NULL, 'Foreign key in zp_account_location; joins to zp_location.location_id.', 'account,location,id,fk,identifier'),
  (21017, 'zp_account_location', 'service_status', 'ACTIVE', 'Business attribute in zp_account_location. Valid values include: ACTIVE.', 'account,location,service,status,column,enum'),
  (21018, 'zp_account_location', 'updated_at', NULL, 'Business attribute in zp_account_location.', 'account,location,updated,at,column,time'),
  (21019, 'zp_billbank_record', NULL, NULL, 'Entity table zp_billbank_record used in Zapper business workflow.', 'billbank,record,table,entity'),
  (21020, 'zp_billbank_record', 'account_id', NULL, 'Foreign key in zp_billbank_record; joins to zp_account.account_id.', 'billbank,record,account,id,fk,identifier'),
  (21021, 'zp_billbank_record', 'bill_cease_status', 'CEASED,ACTIVE', 'Business attribute in zp_billbank_record. Valid values include: CEASED,ACTIVE.', 'billbank,record,bill,cease,status,column,enum'),
  (21022, 'zp_billbank_record', 'bill_plan_code', 'BIZ-FLEX', 'Business attribute in zp_billbank_record. Valid values include: BIZ-FLEX.', 'billbank,record,bill,plan,code,column,enum'),
  (21023, 'zp_billbank_record', 'billbank_id', NULL, 'Primary key for zp_billbank_record.', 'billbank,record,id,pk,identifier'),
  (21024, 'zp_billbank_record', 'current_billing_cost', NULL, 'Business attribute in zp_billbank_record.', 'billbank,record,current,billing,cost,column'),
  (21025, 'zp_billbank_record', 'overdue_amount', NULL, 'Business attribute in zp_billbank_record.', 'billbank,record,overdue,amount,column'),
  (21026, 'zp_billbank_record', 'pending_bill_amount', NULL, 'Business attribute in zp_billbank_record.', 'billbank,record,pending,bill,amount,column'),
  (21027, 'zp_billbank_record', 'record_status', 'CLOSED,OPEN', 'Business attribute in zp_billbank_record. Valid values include: CLOSED,OPEN.', 'billbank,record,status,column,enum'),
  (21028, 'zp_billbank_record', 'termination_fee_amount', NULL, 'Business attribute in zp_billbank_record.', 'billbank,record,termination,fee,amount,column'),
  (21029, 'zp_billbank_record', 'updated_at', NULL, 'Business attribute in zp_billbank_record.', 'billbank,record,updated,at,column,time'),
  (21030, 'zp_billbank_record', 'zapper_id', NULL, 'Foreign key in zp_billbank_record; joins to zp_connection.zapper_id.', 'billbank,record,zapper,id,fk,identifier'),
  (21031, 'zp_billbank_record', 'zp_connection_id', NULL, 'Foreign key in zp_billbank_record; joins to zp_connection.zp_connection_id.', 'billbank,record,zp,connection,id,fk,identifier'),
  (21032, 'zp_billbank_record', 'zp_disconnect_id', NULL, 'Business attribute in zp_billbank_record.', 'billbank,record,zp,disconnect,id,column,identifier'),
  (21033, 'zp_connection', NULL, NULL, 'Entity table zp_connection used in Zapper business workflow.', 'connection,table,entity'),
  (21034, 'zp_connection', 'acc_loc_id', NULL, 'Foreign key in zp_connection; joins to zp_account_location.acc_loc_id.', 'connection,acc,loc,id,fk,identifier'),
  (21035, 'zp_connection', 'account_id', NULL, 'Foreign key in zp_connection; joins to zp_account.account_id.', 'connection,account,id,fk,identifier'),
  (21036, 'zp_connection', 'connected_at', NULL, 'Business attribute in zp_connection.', 'connection,connected,at,column,time'),
  (21037, 'zp_connection', 'connection_order_number', NULL, 'Business attribute in zp_connection.', 'connection,order,number,column'),
  (21038, 'zp_connection', 'connection_status', 'ACTIVE', 'Business attribute in zp_connection. Valid values include: ACTIVE.', 'connection,status,column,enum'),
  (21039, 'zp_connection', 'created_at', NULL, 'Business attribute in zp_connection.', 'connection,created,at,column,time'),
  (21040, 'zp_connection', 'customer_id', NULL, 'Foreign key in zp_connection; joins to zp_customer.customer_id.', 'connection,customer,id,fk,identifier'),
  (21041, 'zp_connection', 'customer_loc_id', NULL, 'Business attribute in zp_connection.', 'connection,customer,loc,id,column,identifier'),
  (21042, 'zp_connection', 'location_id', NULL, 'Foreign key in zp_connection; joins to zp_location.location_id.', 'connection,location,id,fk,identifier'),
  (21043, 'zp_connection', 'updated_at', NULL, 'Business attribute in zp_connection.', 'connection,updated,at,column,time'),
  (21044, 'zp_connection', 'zapper_id', NULL, 'Business attribute in zp_connection.', 'connection,zapper,id,column,identifier'),
  (21045, 'zp_connection', 'zp_connection_id', NULL, 'Primary key for zp_connection.', 'connection,zp,id,pk,identifier'),
  (21046, 'zp_customer', NULL, NULL, 'Entity table zp_customer used in Zapper business workflow.', 'customer,table,entity'),
  (21047, 'zp_customer', 'contact_number', NULL, 'Business attribute in zp_customer.', 'customer,contact,number,column'),
  (21048, 'zp_customer', 'created_at', NULL, 'Business attribute in zp_customer.', 'customer,created,at,column,time'),
  (21049, 'zp_customer', 'customer_id', NULL, 'Primary key for zp_customer.', 'customer,id,pk,identifier'),
  (21050, 'zp_customer', 'customer_name', NULL, 'Business attribute in zp_customer.', 'customer,name,column'),
  (21051, 'zp_customer', 'customer_status', 'ACTIVE', 'Business attribute in zp_customer. Valid values include: ACTIVE.', 'customer,status,column,enum'),
  (21052, 'zp_customer', 'customer_type', 'ENTERPRISE,MID_MARKET', 'Business attribute in zp_customer. Valid values include: ENTERPRISE,MID_MARKET.', 'customer,type,column,enum'),
  (21053, 'zp_customer', 'email_address', NULL, 'Business attribute in zp_customer.', 'customer,email,address,column'),
  (21054, 'zp_customer', 'updated_at', NULL, 'Business attribute in zp_customer.', 'customer,updated,at,column,time'),
  (21055, 'zp_disconnect_order', NULL, NULL, 'Entity table zp_disconnect_order used in Zapper business workflow.', 'disconnect,order,table,entity'),
  (21056, 'zp_disconnect_order', 'acc_loc_id', NULL, 'Foreign key in zp_disconnect_order; joins to zp_account_location.acc_loc_id.', 'disconnect,order,acc,loc,id,fk,identifier'),
  (21057, 'zp_disconnect_order', 'account_id', NULL, 'Foreign key in zp_disconnect_order; joins to zp_account.account_id.', 'disconnect,order,account,id,fk,identifier'),
  (21058, 'zp_disconnect_order', 'created_at', NULL, 'Business attribute in zp_disconnect_order.', 'disconnect,order,created,at,column,time'),
  (21059, 'zp_disconnect_order', 'disconnect_due_at', NULL, 'Business attribute in zp_disconnect_order.', 'disconnect,order,due,at,column,time'),
  (21060, 'zp_disconnect_order', 'don', NULL, 'Primary key for zp_disconnect_order.', 'disconnect,order,don,pk'),
  (21061, 'zp_disconnect_order', 'downstream_status', 'FAILED_TERMINATION_FEE,COMPLETED', 'Business attribute in zp_disconnect_order. Valid values include: FAILED_TERMINATION_FEE,COMPLETED.', 'disconnect,order,downstream,status,column,enum'),
  (21062, 'zp_disconnect_order', 'last_checked_at', NULL, 'Business attribute in zp_disconnect_order.', 'disconnect,order,last,checked,at,column,time'),
  (21063, 'zp_disconnect_order', 'submit_channel', 'ZAPPER_CENTRAL', 'Business attribute in zp_disconnect_order. Valid values include: ZAPPER_CENTRAL.', 'disconnect,order,submit,channel,column,enum'),
  (21064, 'zp_disconnect_order', 'submit_status', 'SUBMITTED', 'Business attribute in zp_disconnect_order. Valid values include: SUBMITTED.', 'disconnect,order,submit,status,column,enum'),
  (21065, 'zp_disconnect_order', 'submitted_at', NULL, 'Business attribute in zp_disconnect_order.', 'disconnect,order,submitted,at,column,time'),
  (21066, 'zp_disconnect_order', 'updated_at', NULL, 'Business attribute in zp_disconnect_order.', 'disconnect,order,updated,at,column,time'),
  (21067, 'zp_disconnect_order', 'zapper_id', NULL, 'Foreign key in zp_disconnect_order; joins to zp_connection.zapper_id.', 'disconnect,order,zapper,id,fk,identifier'),
  (21068, 'zp_disconnect_order', 'zp_connection_id', NULL, 'Foreign key in zp_disconnect_order; joins to zp_connection.zp_connection_id.', 'disconnect,order,zp,connection,id,fk,identifier'),
  (21069, 'zp_disconnect_order', 'zp_disconnect_id', NULL, 'Business attribute in zp_disconnect_order.', 'disconnect,order,zp,id,column,identifier'),
  (21070, 'zp_disconnect_order', 'zp_request_id', NULL, 'Foreign key in zp_disconnect_order; joins to zp_request.zp_request_id.', 'disconnect,order,zp,request,id,fk,identifier'),
  (21071, 'zp_inventory_service', NULL, NULL, 'Entity table zp_inventory_service used in Zapper business workflow.', 'inventory,service,table,entity'),
  (21072, 'zp_inventory_service', 'acc_loc_id', NULL, 'Foreign key in zp_inventory_service; joins to zp_account_location.acc_loc_id.', 'inventory,service,acc,loc,id,fk,identifier'),
  (21073, 'zp_inventory_service', 'account_id', NULL, 'Foreign key in zp_inventory_service; joins to zp_account.account_id.', 'inventory,service,account,id,fk,identifier'),
  (21074, 'zp_inventory_service', 'created_at', NULL, 'Business attribute in zp_inventory_service.', 'inventory,service,created,at,column,time'),
  (21075, 'zp_inventory_service', 'customer_id', NULL, 'Foreign key in zp_inventory_service; joins to zp_customer.customer_id.', 'inventory,service,customer,id,fk,identifier'),
  (21076, 'zp_inventory_service', 'inventory_id', NULL, 'Primary key for zp_inventory_service.', 'inventory,service,id,pk,identifier'),
  (21077, 'zp_inventory_service', 'inventory_status', NULL, 'Business attribute in zp_inventory_service.', 'inventory,service,status,column,enum'),
  (21078, 'zp_inventory_service', 'inventory_sync_status', NULL, 'Business attribute in zp_inventory_service.', 'inventory,service,sync,status,column,enum'),
  (21079, 'zp_inventory_service', 'last_verified_at', NULL, 'Business attribute in zp_inventory_service.', 'inventory,service,last,verified,at,column,time'),
  (21080, 'zp_inventory_service', 'provisioned_flag', NULL, 'Business attribute in zp_inventory_service.', 'inventory,service,provisioned,flag,column'),
  (21081, 'zp_inventory_service', 'updated_at', NULL, 'Business attribute in zp_inventory_service.', 'inventory,service,updated,at,column,time'),
  (21082, 'zp_inventory_service', 'zapper_id', NULL, 'Foreign key in zp_inventory_service; joins to zp_connection.zapper_id.', 'inventory,service,zapper,id,fk,identifier'),
  (21083, 'zp_inventory_service', 'zp_connection_id', NULL, 'Foreign key in zp_inventory_service; joins to zp_connection.zp_connection_id.', 'inventory,service,zp,connection,id,fk,identifier'),
  (21084, 'zp_location', NULL, NULL, 'Entity table zp_location used in Zapper business workflow.', 'location,table,entity'),
  (21085, 'zp_location', 'city_name', NULL, 'Business attribute in zp_location.', 'location,city,name,column'),
  (21086, 'zp_location', 'created_at', NULL, 'Business attribute in zp_location.', 'location,created,at,column,time'),
  (21087, 'zp_location', 'location_id', NULL, 'Primary key for zp_location.', 'location,id,pk,identifier'),
  (21088, 'zp_location', 'location_name', NULL, 'Business attribute in zp_location.', 'location,name,column'),
  (21089, 'zp_location', 'service_address', NULL, 'Business attribute in zp_location.', 'location,service,address,column'),
  (21090, 'zp_location', 'state_code', 'TX', 'Business attribute in zp_location. Valid values include: TX.', 'location,state,code,column,enum'),
  (21091, 'zp_location', 'updated_at', NULL, 'Business attribute in zp_location.', 'location,updated,at,column,time'),
  (21092, 'zp_location', 'zip_code', '75061,75201,73301,75024', 'Business attribute in zp_location. Valid values include: 75061,75201,73301,75024.', 'location,zip,code,column,enum'),
  (21093, 'zp_location_validation', NULL, NULL, 'Entity table zp_location_validation used in Zapper business workflow.', 'location,validation,table,entity'),
  (21094, 'zp_location_validation', 'location_id', NULL, 'Foreign key in zp_location_validation; joins to zp_location.location_id.', 'location,validation,id,fk,identifier'),
  (21095, 'zp_location_validation', 'validated_at', NULL, 'Business attribute in zp_location_validation.', 'location,validation,validated,at,column,time,identifier'),
  (21096, 'zp_location_validation', 'validated_zip_code', '75061,73301,75201,75024', 'Business attribute in zp_location_validation. Valid values include: 75061,73301,75201,75024.', 'location,validation,validated,zip,code,column,enum,identifier'),
  (21097, 'zp_location_validation', 'validation_id', NULL, 'Primary key for zp_location_validation.', 'location,validation,id,pk,identifier'),
  (21098, 'zp_location_validation', 'validation_status', 'VALID', 'Business attribute in zp_location_validation. Valid values include: VALID.', 'location,validation,status,column,enum,identifier'),
  (21099, 'zp_location_validation', 'zip_match_flag', 'true', 'Business attribute in zp_location_validation. Valid values include: true.', 'location,validation,zip,match,flag,column'),
  (21100, 'zp_location_validation', 'zp_request_id', NULL, 'Business attribute in zp_location_validation.', 'location,validation,zp,request,id,column,identifier'),
  (21101, 'zp_notification_event', NULL, NULL, 'Entity table zp_notification_event used in Zapper business workflow.', 'notification,event,table,entity'),
  (21102, 'zp_notification_event', 'created_at', NULL, 'Business attribute in zp_notification_event.', 'notification,event,created,at,column,time'),
  (21103, 'zp_notification_event', 'don', NULL, 'Foreign key in zp_notification_event; joins to zp_disconnect_order.don.', 'notification,event,don,fk'),
  (21104, 'zp_notification_event', 'notification_id', NULL, 'Primary key for zp_notification_event.', 'notification,event,id,pk,identifier'),
  (21105, 'zp_notification_event', 'notification_status', 'SENT,PENDING', 'Business attribute in zp_notification_event. Valid values include: SENT,PENDING.', 'notification,event,status,column,enum'),
  (21106, 'zp_notification_event', 'notification_type', 'ASO_SLA_BREACH,BILLBANK_SYNC_ALERT', 'Business attribute in zp_notification_event. Valid values include: ASO_SLA_BREACH,BILLBANK_SYNC_ALERT.', 'notification,event,type,column,enum'),
  (21107, 'zp_notification_event', 'recipient_email', NULL, 'Business attribute in zp_notification_event.', 'notification,event,recipient,email,column'),
  (21108, 'zp_notification_event', 'sent_at', NULL, 'Business attribute in zp_notification_event.', 'notification,event,sent,at,column,time'),
  (21109, 'zp_notification_event', 'zp_request_id', NULL, 'Foreign key in zp_notification_event; joins to zp_request.zp_request_id.', 'notification,event,zp,request,id,fk,identifier'),
  (21110, 'zp_order_downstream_check', NULL, NULL, 'Entity table zp_order_downstream_check used in Zapper business workflow.', 'order,downstream,check,table,entity'),
  (21111, 'zp_order_downstream_check', 'check_code', 'ORDER_VALIDATION,BILL_CEASE,TERMINATION_FEE', 'Business attribute in zp_order_downstream_check. Valid values include: ORDER_VALIDATION,BILL_CEASE,TERMINATION_FEE.', 'order,downstream,check,code,column,enum'),
  (21112, 'zp_order_downstream_check', 'check_id', NULL, 'Primary key for zp_order_downstream_check.', 'order,downstream,check,id,pk,identifier'),
  (21113, 'zp_order_downstream_check', 'check_label', NULL, 'Business attribute in zp_order_downstream_check.', 'order,downstream,check,label,column'),
  (21114, 'zp_order_downstream_check', 'check_status', 'PASS,FAIL', 'Business attribute in zp_order_downstream_check. Valid values include: PASS,FAIL.', 'order,downstream,check,status,column,enum'),
  (21115, 'zp_order_downstream_check', 'checked_at', NULL, 'Business attribute in zp_order_downstream_check.', 'order,downstream,check,checked,at,column,time'),
  (21116, 'zp_order_downstream_check', 'don', NULL, 'Foreign key in zp_order_downstream_check; joins to zp_disconnect_order.don.', 'order,downstream,check,don,fk'),
  (21117, 'zp_order_downstream_check', 'failure_reason', NULL, 'Business attribute in zp_order_downstream_check.', 'order,downstream,check,failure,reason,column'),
  (21118, 'zp_request', NULL, NULL, 'Entity table zp_request used in Zapper business workflow.', 'request,table,entity'),
  (21119, 'zp_request', 'acc_loc_id', NULL, 'Foreign key in zp_request; joins to zp_account_location.acc_loc_id.', 'request,acc,loc,id,fk,identifier'),
  (21120, 'zp_request', 'account_id', NULL, 'Foreign key in zp_request; joins to zp_account.account_id.', 'request,account,id,fk,identifier'),
  (21121, 'zp_request', 'created_at', NULL, 'Business attribute in zp_request.', 'request,created,at,column,time'),
  (21122, 'zp_request', 'customer_id', NULL, 'Foreign key in zp_request; joins to zp_customer.customer_id.', 'request,customer,id,fk,identifier'),
  (21123, 'zp_request', 'location_id', NULL, 'Foreign key in zp_request; joins to zp_location.location_id.', 'request,location,id,fk,identifier'),
  (21124, 'zp_request', 'request_status', 'REJECTED,INVENTORY_ERROR,SUBMITTED,COMPLETED', 'Business attribute in zp_request. Valid values include: REJECTED,INVENTORY_ERROR,SUBMITTED,COMPLETED.', 'request,status,column,enum'),
  (21125, 'zp_request', 'request_type', 'DISCONNECT', 'Business attribute in zp_request. Valid values include: DISCONNECT.', 'request,type,column,enum'),
  (21126, 'zp_request', 'requested_at', NULL, 'Business attribute in zp_request.', 'request,requested,at,column,time'),
  (21127, 'zp_request', 'requested_provider', 'GEXXA', 'Business attribute in zp_request. Valid values include: GEXXA.', 'request,requested,provider,column,enum,identifier'),
  (21128, 'zp_request', 'submitted_to_aso_at', NULL, 'Business attribute in zp_request.', 'request,submitted,to,aso,at,column,time'),
  (21129, 'zp_request', 'updated_at', NULL, 'Business attribute in zp_request.', 'request,updated,at,column,time'),
  (21130, 'zp_request', 'zp_connection_id', NULL, 'Foreign key in zp_request; joins to zp_connection.zp_connection_id.', 'request,zp,connection,id,fk,identifier'),
  (21131, 'zp_request', 'zp_contact_number', NULL, 'Business attribute in zp_request.', 'request,zp,contact,number,column'),
  (21132, 'zp_request', 'zp_cust_zip', NULL, 'Business attribute in zp_request.', 'request,zp,cust,zip,column'),
  (21133, 'zp_request', 'zp_customer_name', NULL, 'Business attribute in zp_request.', 'request,zp,customer,name,column'),
  (21134, 'zp_request', 'zp_request_id', NULL, 'Primary key for zp_request.', 'request,zp,id,pk,identifier'),
  (21135, 'zp_ui_data', NULL, NULL, 'Entity table zp_ui_data used in Zapper business workflow.', 'ui,data,table,entity'),
  (21136, 'zp_ui_data', 'last_updated_at', NULL, 'Business attribute in zp_ui_data.', 'ui,data,last,updated,at,column,time'),
  (21137, 'zp_ui_data', 'zp_action_id', '400,200,500', 'Business attribute in zp_ui_data. Valid values include: 400,200,500.', 'ui,data,zp,action,id,column,enum,identifier'),
  (21138, 'zp_ui_data', 'zp_asr_team_member_id', NULL, 'Business attribute in zp_ui_data.', 'ui,data,zp,asr,team,member,id,column,identifier'),
  (21139, 'zp_ui_data', 'zp_asr_team_notes', NULL, 'Business attribute in zp_ui_data.', 'ui,data,zp,asr,team,notes,column'),
  (21140, 'zp_ui_data', 'zp_queue_code', 'ASR_REJECTED,ASR_ASSIGNED,ASO_SUBMITTED,ASO_COMPLETED', 'Business attribute in zp_ui_data. Valid values include: ASR_REJECTED,ASR_ASSIGNED,ASO_SUBMITTED,ASO_COMPLETED.', 'ui,data,zp,queue,code,column,enum'),
  (21141, 'zp_ui_data', 'zp_request_id', NULL, 'Primary key for zp_ui_data; also references zp_request.zp_request_id.', 'ui,data,zp,request,id,pk,identifier'),
  (21142, 'zp_ui_data_history', NULL, NULL, 'Entity table zp_ui_data_history used in Zapper business workflow.', 'ui,data,history,table,entity'),
  (21143, 'zp_ui_data_history', 'changed_by', NULL, 'Business attribute in zp_ui_data_history.', 'ui,data,history,changed,by,column'),
  (21144, 'zp_ui_data_history', 'created_date', NULL, 'Business attribute in zp_ui_data_history.', 'ui,data,history,created,date,column,time'),
  (21145, 'zp_ui_data_history', 'history_id', NULL, 'Primary key for zp_ui_data_history.', 'ui,data,history,id,pk,identifier'),
  (21146, 'zp_ui_data_history', 'zp_action_id', '100,200,400,300,500', 'Business attribute in zp_ui_data_history. Valid values include: 100,200,400,300,500.', 'ui,data,history,zp,action,id,column,enum,identifier'),
  (21147, 'zp_ui_data_history', 'zp_asr_team_member_id', NULL, 'Business attribute in zp_ui_data_history.', 'ui,data,history,zp,asr,team,member,id,column,identifier'),
  (21148, 'zp_ui_data_history', 'zp_asr_team_notes', NULL, 'Business attribute in zp_ui_data_history.', 'ui,data,history,zp,asr,team,notes,column'),
  (21149, 'zp_ui_data_history', 'zp_request_id', NULL, 'Foreign key in zp_ui_data_history; joins to zp_request.zp_request_id.', 'ui,data,history,zp,request,id,fk,identifier')
ON CONFLICT (id) DO UPDATE SET
  table_name = EXCLUDED.table_name,
  column_name = EXCLUDED.column_name,
  valid_values = EXCLUDED.valid_values,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags;
