CREATE TABLE ce_config (
  config_id NUMBER(10) NOT NULL,
  config_type VARCHAR2(255) NOT NULL,
  config_key VARCHAR2(255) NOT NULL,
  config_value CLOB NOT NULL,
  enabled NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT ce_config_pkey PRIMARY KEY (config_id)
);
CREATE UNIQUE INDEX ux_ce_config_type_key ON ce_config (config_type, config_key);

CREATE TABLE ce_container_config (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intent_code VARCHAR2(255) NOT NULL,
  state_code VARCHAR2(255) NOT NULL,
  page_id NUMBER(10) NOT NULL,
  section_id NUMBER(10) NOT NULL,
  container_id NUMBER(10) NOT NULL,
  input_param_name VARCHAR2(255) NOT NULL,
  priority NUMBER(10) DEFAULT 1 NOT NULL,
  enabled NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_ce_validation_config_lookup ON ce_container_config (intent_code, state_code, enabled, priority);

CREATE TABLE ce_conversation (
  conversation_id VARCHAR2(36) NOT NULL,
  status VARCHAR2(255) NOT NULL,
  intent_code VARCHAR2(255),
  state_code VARCHAR2(255) NOT NULL,
  context_json CLOB DEFAULT '{}' NOT NULL,
  last_user_text CLOB,
  last_assistant_json CLOB,
  input_params_json CLOB DEFAULT '{}' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT ce_conversation_pkey PRIMARY KEY (conversation_id)
);
CREATE INDEX idx_ce_conversation_status ON ce_conversation (status);
CREATE INDEX idx_ce_conversation_updated ON ce_conversation (updated_at);

CREATE TABLE ce_intent (
  intent_code VARCHAR2(255) NOT NULL,
  description CLOB NOT NULL,
  priority NUMBER(10) DEFAULT 100 NOT NULL,
  enabled NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  display_name VARCHAR2(255),
  llm_hint CLOB,
  CONSTRAINT ce_intent_pkey PRIMARY KEY (intent_code)
);
CREATE INDEX ix_ce_intent_enabled_priority ON ce_intent (enabled, priority, intent_code);

CREATE TABLE ce_intent_classifier (
  classifier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intent_code VARCHAR2(255) NOT NULL,
  rule_type VARCHAR2(100) NOT NULL,
  pattern CLOB NOT NULL,
  priority NUMBER(10) NOT NULL,
  enabled NUMBER(1) DEFAULT 1,
  description CLOB
);

CREATE TABLE ce_llm_call_log (
  llm_call_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id VARCHAR2(36) NOT NULL,
  intent_code VARCHAR2(255),
  state_code VARCHAR2(255),
  provider VARCHAR2(255) NOT NULL,
  model VARCHAR2(255) NOT NULL,
  temperature NUMBER(3,2),
  prompt_text CLOB NOT NULL,
  user_context CLOB NOT NULL,
  response_text CLOB,
  success NUMBER(1) NOT NULL,
  error_message CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_ce_llm_log_conversation ON ce_llm_call_log (conversation_id);
CREATE INDEX idx_ce_llm_log_intent_state ON ce_llm_call_log (intent_code, state_code);

CREATE TABLE ce_mcp_tool (
  tool_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_code VARCHAR2(255) NOT NULL,
  tool_group VARCHAR2(255) NOT NULL,
  enabled NUMBER(1) DEFAULT 1 NOT NULL,
  description CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT ce_mcp_tool_tool_code_key UNIQUE (tool_code)
);
CREATE INDEX idx_ce_mcp_tool_enabled ON ce_mcp_tool (enabled, tool_group, tool_code);

CREATE TABLE ce_output_schema (
  schema_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intent_code VARCHAR2(255) NOT NULL,
  state_code VARCHAR2(255) NOT NULL,
  json_schema CLOB NOT NULL,
  description CLOB,
  enabled NUMBER(1) DEFAULT 1,
  priority NUMBER(10) NOT NULL
);
CREATE INDEX idx_ce_output_schema_lookup ON ce_output_schema (intent_code, state_code, enabled, priority);

CREATE TABLE ce_policy (
  policy_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_type VARCHAR2(100) NOT NULL,
  pattern CLOB NOT NULL,
  response_text CLOB NOT NULL,
  priority NUMBER(10) DEFAULT 10 NOT NULL,
  enabled NUMBER(1) DEFAULT 1 NOT NULL,
  description CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_ce_policy_priority ON ce_policy (enabled, priority);

CREATE TABLE ce_prompt_template (
  template_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intent_code VARCHAR2(255),
  state_code VARCHAR2(255),
  response_type VARCHAR2(50) NOT NULL,
  system_prompt CLOB NOT NULL,
  user_prompt CLOB NOT NULL,
  temperature NUMBER(3,2) DEFAULT 0.0 NOT NULL,
  enabled NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_ce_prompt_template_lookup ON ce_prompt_template (response_type, intent_code, state_code, enabled);

CREATE TABLE ce_response (
  response_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intent_code VARCHAR2(255),
  state_code VARCHAR2(255) NOT NULL,
  output_format VARCHAR2(50) NOT NULL,
  response_type VARCHAR2(50) NOT NULL,
  exact_text CLOB,
  derivation_hint CLOB,
  json_schema CLOB,
  priority NUMBER(10) DEFAULT 100 NOT NULL,
  enabled NUMBER(1) DEFAULT 1 NOT NULL,
  description CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_ce_response_intent_state ON ce_response (intent_code, state_code, enabled, priority);
CREATE INDEX idx_ce_response_lookup ON ce_response (state_code, enabled, priority);

CREATE TABLE ce_rule (
  rule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phase VARCHAR2(100) DEFAULT 'PIPELINE_RULES' NOT NULL,
  intent_code VARCHAR2(255),
  state_code VARCHAR2(255),
  rule_type VARCHAR2(100) NOT NULL,
  match_pattern CLOB NOT NULL,
  action VARCHAR2(255) NOT NULL,
  action_value CLOB,
  priority NUMBER(10) DEFAULT 100 NOT NULL,
  enabled NUMBER(1) DEFAULT 1 NOT NULL,
  description CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_ce_rule_priority ON ce_rule (enabled, phase, state_code, priority);

CREATE TABLE ce_pending_action (
  pending_action_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intent_code VARCHAR2(255),
  state_code VARCHAR2(255),
  action_key VARCHAR2(255) NOT NULL,
  bean_name VARCHAR2(255) NOT NULL,
  method_names CLOB NOT NULL,
  priority NUMBER(10) DEFAULT 100 NOT NULL,
  enabled NUMBER(1) DEFAULT 1 NOT NULL,
  description CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_ce_pending_action_lookup ON ce_pending_action (enabled, action_key, intent_code, state_code, priority);

CREATE TABLE ce_validation_snapshot (
  snapshot_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id VARCHAR2(36) NOT NULL,
  intent_code VARCHAR2(64),
  state_code VARCHAR2(64),
  validation_tables CLOB,
  validation_decision CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  schema_id NUMBER(19)
);
CREATE INDEX idx_ce_validation_snapshot_conv ON ce_validation_snapshot (conversation_id);

CREATE TABLE ce_audit (
  audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id VARCHAR2(36) NOT NULL,
  stage VARCHAR2(255) NOT NULL,
  payload_json CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT ce_audit_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES ce_conversation(conversation_id) ON DELETE CASCADE
);
CREATE INDEX idx_ce_audit_conversation ON ce_audit (conversation_id, created_at DESC);

CREATE TABLE ce_conversation_history (
  history_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id VARCHAR2(36) NOT NULL,
  entry_type VARCHAR2(100) NOT NULL,
  role VARCHAR2(50) NOT NULL,
  stage VARCHAR2(255) NOT NULL,
  content_text CLOB,
  payload_json CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT ce_conversation_history_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES ce_conversation(conversation_id) ON DELETE CASCADE
);
CREATE INDEX idx_ce_conversation_history_conv ON ce_conversation_history (conversation_id, created_at DESC);

CREATE TABLE ce_mcp_db_tool (
  tool_id NUMBER(19) NOT NULL,
  dialect VARCHAR2(64) DEFAULT 'POSTGRES' NOT NULL,
  sql_template CLOB NOT NULL,
  param_schema CLOB NOT NULL,
  safe_mode NUMBER(1) DEFAULT 1 NOT NULL,
  max_rows NUMBER(10) DEFAULT 200 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  allowed_identifiers CLOB,
  CONSTRAINT ce_mcp_db_tool_pkey PRIMARY KEY (tool_id),
  CONSTRAINT ce_mcp_db_tool_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES ce_mcp_tool(tool_id) ON DELETE CASCADE
);
CREATE INDEX idx_ce_mcp_db_tool_dialect ON ce_mcp_db_tool (dialect);
