package com.github.salilvnair.convengine.audit;

public enum ConvEngineAuditStage {
    USER_INPUT,
    DIALOGUE_ACT_CLASSIFIED,
    INTERACTION_POLICY_DECIDED,
    PENDING_ACTION_SKIPPED,
    PENDING_ACTION_EXECUTED,
    PENDING_ACTION_REJECTED,
    PENDING_ACTION_FAILED,
    PENDING_ACTION_LIFECYCLE,
    DISAMBIGUATION_REQUIRED,
    GUARDRAIL_ALLOW,
    GUARDRAIL_DENY,
    STATE_GRAPH_VALID,
    STATE_GRAPH_VIOLATION,
    TOOL_ORCHESTRATION_REQUEST,
    TOOL_ORCHESTRATION_RESULT,
    TOOL_ORCHESTRATION_ERROR,
    MEMORY_UPDATED,
    INTENT_MISSING,
    STATE_MISSING,
    INTENT_RESOLVE_START,
    INTENT_RESOLVE_SKIPPED_SCHEMA_COLLECTION,
    INTENT_RESOLVE_SKIPPED_STICKY_INTENT,
    INTENT_RESOLVE_SKIPPED_POLICY,
    INTENT_RESOLVE_NO_CHANGE,
    INTENT_CLASSIFIER_COLLISION,
    INTENT_CLASSIFICATION_MATCHED,
    INTENT_CLASSIFIER_NO_MATCH,
    INTENT_AGENT_SKIPPED,
    INTENT_AGENT_LLM_INPUT,
    INTENT_AGENT_LLM_OUTPUT,
    INTENT_AGENT_REJECTED,
    INTENT_AGENT_SCORES,
    INTENT_AGENT_COLLISION,
    INTENT_AGENT_CLARIFICATION_SUPPRESSED_SCHEMA_FLOW,
    INTENT_AGENT_NEEDS_CLARIFICATION,
    INTENT_AGENT_ACCEPTED,
    INTENT_COLLISION_DETECTED,
    INTENT_COLLISION_RESOLVED,
    SCHEMA_EXTRACTION_START,
    SCHEMA_EXTRACTION_LLM_INPUT,
    SCHEMA_EXTRACTION_LLM_OUTPUT,
    SCHEMA_STATUS,
    RESOLVE_RESPONSE,
    RESPONSE_MAPPING_NOT_FOUND,
    RESOLVE_RESPONSE_SELECTED,
    RESOLVE_RESPONSE_LLM_INPUT,
    RESOLVE_RESPONSE_LLM_OUTPUT,
    RESPONSE_EXACT,
    ASSISTANT_OUTPUT,
    AUTO_ADVANCE_SKIPPED_NO_SCHEMA,
    AUTO_ADVANCE_FACTS,
    POLICY_BLOCK,
    MCP_SKIPPED_PENDING_CLARIFICATION,
    MCP_NO_TOOLS_AVAILABLE,
    MCP_PLAN_LLM_INPUT,
    MCP_PLAN_LLM_OUTPUT,
    MCP_TOOL_CALL,
    MCP_TOOL_RESULT,
    MCP_TOOL_ERROR,
    MCP_FINAL_ANSWER,
    CONVERSATION_RESET,
    PIPELINE_TIMING,
    CACHE_INSPECTION,
    ENGINE_RETURN,
    RULE_MATCH,
    RULE_APPLIED,
    RULE_NO_MATCH,
    PROMPT_RENDERING

    ;

    public String value() {
        return name();
    }

    public String withStage(String stage) {
        if (stage == null || stage.isBlank()) {
            return value();
        }
        return value() + " (" + stage + ")";
    }

    public static String intentResolvedBy(String source) {
        if (source == null || source.isBlank()) {
            return "INTENT_RESOLVED_BY_UNKNOWN";
        }
        return "INTENT_RESOLVED_BY_" + source.trim().toUpperCase();
    }
}
