-- Seed file for Schema-Aware LLM SQL Extension
-- This registers the tool, the planner, and sample knowledge without colliding with existing DBKG

-- ==========================================
-- 1. Create a specific test intent for dynamic SQL
-- ==========================================
DELETE FROM ce_intent WHERE intent_code = 'dynamic_sql';
INSERT INTO ce_intent (intent_code, description, display_name, llm_hint, priority, enabled, created_at)
VALUES ('dynamic_sql', 'Dynamic SQL Execution Flow', 'Dynamic DB Query', 'Use this intent to run dynamic SQL queries based on db knowledge.', 100, true, CURRENT_TIMESTAMP);

-- ==========================================
-- 1b. Assign a deterministic Classifier Rule so you can easily invoke it
--     Type: "/sql Find all rejected requests" to force this intent.
-- ==========================================
DELETE FROM ce_intent_classifier WHERE intent_code = 'dynamic_sql';
INSERT INTO ce_intent_classifier(
    intent_code, state_code, rule_type, pattern, priority, enabled, description
) VALUES
    ('dynamic_sql', 'UNKNOWN', 'STARTS_WITH', '/sql', 10, true, 'Force routing to the dynamic sql planner');

-- ==========================================
-- 2. State Rules
-- ==========================================
DELETE FROM ce_rule WHERE intent_code = 'dynamic_sql';
-- Rule 1: Move from UNKNOWN/IDLE to EXECUTE
INSERT INTO ce_rule (phase, intent_code, state_code, rule_type, match_pattern, "action", action_value, priority, enabled, description, created_at) VALUES
    ('POST_AGENT_INTENT', 'dynamic_sql', 'IDLE', 'EXACT', 'ANY', 'SET_STATE', 'EXECUTE', 10, true, 'Enter EXECUTE state.', CURRENT_TIMESTAMP);
-- Rule 2: Move from EXECUTE to COMPLETED when MCP finishes
INSERT INTO ce_rule (phase, intent_code, state_code, rule_type, match_pattern, "action", action_value, priority, enabled, description, created_at) VALUES
    ('POST_AGENT_MCP', 'dynamic_sql', 'EXECUTE', 'JSON_PATH', '$[?(@.context.mcp.lifecycle.finished==true)]', 'SET_STATE', 'COMPLETED', 10, true, 'Close dynamic SQL flow after MCP.', CURRENT_TIMESTAMP);

-- ==========================================
-- 3. Prompt Templates
-- ==========================================
DELETE FROM ce_prompt_template WHERE intent_code = 'dynamic_sql';
-- Prompt 1: Final summary response when the task completes
INSERT INTO ce_prompt_template(intent_code, state_code, response_type, system_prompt, user_prompt, temperature, enabled, created_at, interaction_mode, interaction_contract)
VALUES
    ('dynamic_sql', 'COMPLETED', 'DERIVED', 'You are a database expert.', 'Context JSON:
{{context}}

Use context.mcp.finalAnswer as primary final answer to the user.
Use context.mcp.observations only to validate details if needed.', 0.00, true, CURRENT_TIMESTAMP, 'FINAL', '{"allows":["summarize"],"expects":["mcp_final_answer"]}');

-- ==========================================
-- 4. Responses
-- ==========================================
DELETE FROM ce_response WHERE intent_code = 'dynamic_sql';
-- Response 1: Derived final response mapping to the COMPLETED state
INSERT INTO ce_response(intent_code, state_code, output_format, response_type, exact_text, derivation_hint, priority, enabled, description, created_at)
VALUES
    ('dynamic_sql', 'COMPLETED', 'TEXT', 'DERIVED', NULL, 'Render final answer from context.mcp.finalAnswer.', 10, true, 'Final dynamic SQL response.', CURRENT_TIMESTAMP);

-- ==========================================
-- 5. Register the custom SQL Execution Tool globally (ANY intent/state)
-- ==========================================
DELETE FROM ce_mcp_tool WHERE tool_code = 'postgres.query';
INSERT INTO ce_mcp_tool(
    tool_code, tool_group, intent_code, state_code, description, enabled, created_at
) VALUES (
             'postgres.query', 'DB', 'ANY', 'ANY', 'Execute raw read-only Postgres SQL generated by the LLM.', true, CURRENT_TIMESTAMP
         );

-- ==========================================
-- 6. Configure a specific MCP Planner ONLY for the 'dynamic_sql' intent
-- ==========================================
DELETE FROM ce_mcp_planner WHERE intent_code = 'dynamic_sql';
INSERT INTO ce_mcp_planner(
    intent_code, state_code, system_prompt, user_prompt, enabled, created_at
) VALUES (
             'dynamic_sql', 'EXECUTE',
             'You are a DB expert. Your task is to plan table investigations.
         You have two main tools available:
         1. `db.semantic.catalog` - Pass keywords here to learn about tables, their columns, and see sample SQL queries before formulating your own.
         2. `postgres.query` - Pass the raw SELECT SQL query here once you know exactly what tables and columns to query.

         You must follow these steps:
         1. If you do not know the exact schema or queries for the users request, invoke `db.semantic.catalog` to get hints.
         2. Based on the domain semantic knowledge, generate a safe and read-only SELECT query.
         3. Submit the SQL query to `postgres.query`.
         4. Based on the returned rows, answer the user.
         5. Use type-safe time handling:
            - If a column is TIMESTAMP/TIMESTAMPTZ/DATE, compare it directly to timestamp/date expressions. Do NOT divide by 1000.
            - Use epoch conversion only when the source column is numeric epoch milliseconds (BIGINT/NUMERIC), then use to_timestamp(epoch_ms/1000.0).
            - Never compare timestamp columns with numeric epoch expressions.
         6. Never invent table or column names. Use only columns present in DBKG capsule/schema knowledge/query knowledge.
            For `zp_ui_data_history`, use `created_date` for time filters, not `zp_action_ts`.
         7. DBKG capsule is preloaded from ce_mcp_* metadata tables for this flow. Do not call any dbkg.* tool codes in this dynamic_sql planner.

         Return JSON only. Action MUST be exactly CALL_TOOL or ANSWER.
         Use this exact schema:
         {
           "action": "CALL_TOOL" | "ANSWER",
           "tool_code": "<tool_code_or_null>",
           "args": {},
           "answer": "<text_or_null>"
         }

         Tool argument contract:
         - For db.semantic.catalog use args.question as a single plain text question.
         - For postgres.query use args.query and it must be a read-only SELECT statement.
         - When action is ANSWER, set tool_code to null and args to {}.
         - Final answer must report human-readable date/time values, never raw epoch milliseconds.
         - For "yesterday", use day boundary filters:
           ts_col >= date_trunc(''day'', now() - interval ''1 day'')
           AND ts_col <  date_trunc(''day'', now())
         - Prefer DBKG capsule metadata (tables, columns, joins, templates, status dictionaries, lineage, playbook graph) over raw observation dumps.
         - Allowed tool_code values in this flow: db.semantic.catalog, postgres.query, or null for ANSWER.',
             'User request: {{user_input}}

         Available tools:
         {{available_tools}}

         DBKG capsule (compact metadata context):
         {{dbkg_capsule}}

         Existing context:
         {{mcp_observations}}

         Use DBKG capsule as primary grounding context and use mcp_observations only as compact execution trace.
         Do not return any dbkg.* tool_code in this flow.
         Decide one next step and return strict JSON only with action CALL_TOOL or ANSWER.',
             true, CURRENT_TIMESTAMP
         );

-- ==========================================
-- 4. Seed Schema Semantic Knowledge
--    Tell the LLM what the tables and columns mean
-- ==========================================
DELETE FROM ce_mcp_schema_knowledge;
INSERT INTO ce_mcp_schema_knowledge(
    id, table_name, column_name, description, tags
) VALUES
      (1, 'zp_request', NULL, 'Primary table storing customer provisioning requests', 'request, order, core'),
      (2, 'zp_request', 'zp_request_id', 'Unique request identifier. Used as the primary key and join key across all tables.', 'pk, join_key'),
      (3, 'zp_ui_data', NULL, 'Current state data for UI interactions. Holds the latest status or action code for the request.', 'state, status, latest'),
      (4, 'zp_ui_data_history', NULL, 'Historical log of UI state changes and assignments. Use this table for audits or finding when a request moved from one state to another (e.g. ASSIGNED to REJECTED). Compare different rows with the same zp_request_id but different action_ids over time.', 'history, audit, transition'),
      (5, 'zp_ui_data_history', 'history_id', 'Primary key for history row.', 'pk, history'),
      (6, 'zp_ui_data_history', 'zp_request_id', 'Request id associated with this status transition row.', 'join_key, request'),
      (7, 'zp_ui_data_history', 'zp_action_id', 'Action/status code at this transition point.', 'status, action'),
      (8, 'zp_ui_data_history', 'zp_asr_team_member_id', 'ASR team member id handling this action.', 'asr, owner, assignee'),
      (9, 'zp_ui_data_history', 'zp_asr_team_notes', 'ASR notes/comments for this transition.', 'asr, notes, comments'),
      (10, 'zp_ui_data_history', 'changed_by', 'Actor or system that changed this history row.', 'audit, actor'),
      (11, 'zp_ui_data_history', 'created_date', 'Transition timestamp (TIMESTAMPTZ). Use this for time filters such as yesterday.', 'timestamp, time, transition');

-- ==========================================
-- 5. Seed Query Semantic Knowledge
--    Provide sample queries the LLM can adapt
-- ==========================================
DELETE FROM ce_mcp_query_knowledge;
INSERT INTO ce_mcp_query_knowledge(
    id, query_text, description, prepared_sql, tags, api_hints
) VALUES
    (1, 'Find Rejected Requests recently', 'Finds requests that transitioned from ASR assigned to rejected in the last 24 hours. Replace the action_ids with appropriate values based on the status dictionary if known.',
     'SELECT h2.zp_request_id,
             to_char(h1.created_date AT TIME ZONE ''UTC'', ''YYYY-MM-DD HH24:MI:SS'') AS assigned_at_utc,
             to_char(h2.created_date AT TIME ZONE ''UTC'', ''YYYY-MM-DD HH24:MI:SS'') AS rejected_at_utc
      FROM zp_ui_data_history h1
      JOIN zp_ui_data_history h2 ON h1.zp_request_id = h2.zp_request_id AND h1.created_date < h2.created_date
      WHERE h1.zp_action_id = ''200'' AND h2.zp_action_id = ''400''
      AND h2.created_date >= date_trunc(''day'', now() - interval ''1 day'')
      AND h2.created_date <  date_trunc(''day'', now())
      ORDER BY h2.created_date DESC',
     'rejected, recently, history, state_change', NULL);

-- Make sure db.semantic.catalog is available globally
INSERT INTO ce_mcp_tool(
    tool_code, tool_group, intent_code, state_code, description, enabled, created_at
) SELECT 'db.semantic.catalog', 'DB', 'ANY', 'ANY', 'Semantic query/schema knowledge retrieval for similar issue diagnosis', true, CURRENT_TIMESTAMP
    WHERE NOT EXISTS (SELECT 1 FROM ce_mcp_tool WHERE tool_code = 'db.semantic.catalog');
