package com.github.salilvnair.convengine.engine.mcp.executor.interceptor;

import com.github.salilvnair.convengine.engine.session.EngineSession;
import com.github.salilvnair.convengine.entity.CeMcpTool;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Component;

import java.time.Year;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Default lowest-priority normalizer for postgres.query.
 *
 * Fixes common bad pattern generated by LLM:
 *   to_timestamp(ts_col/1000.0)
 * where ts_col is already timestamp/date typed.
 */
@Slf4j
@Component
@Order()
@RequiredArgsConstructor
public class DefaultPostgresQueryInterceptor implements PostgresQueryInterceptor {

    private static final Pattern FROM_JOIN_ALIAS = Pattern.compile(
            "(?i)\\b(?:from|join)\\s+([a-zA-Z0-9_$.\"]+)\\s+([a-zA-Z0-9_\"]+)");

    private static final Pattern TO_TIMESTAMP_EPOCH_EXPR = Pattern.compile(
            "(?i)to_timestamp\\(\\s*([a-zA-Z_][a-zA-Z0-9_]*)\\.([a-zA-Z_][a-zA-Z0-9_]*)\\s*/\\s*1000(?:\\.0+)?\\s*\\)");
    private static final Pattern DATE_TIME_LITERAL = Pattern.compile(
            "'(\\d{4})-(\\d{2})-(\\d{2})([^']*)'");

    private final NamedParameterJdbcTemplate jdbcTemplate;

    @Override
    public String intercept(String sql, CeMcpTool tool, EngineSession session, Map<String, Object> args) {
        if (sql == null || sql.isBlank()) {
            return sql;
        }

        String normalizedDates = normalizeInvalidDateLiterals(sql);
        if (!normalizedDates.equals(sql)) {
            log.warn("postgres.query interceptor rewrote invalid date literal(s). original={}, rewritten={}", sql, normalizedDates);
            sql = normalizedDates;
        }

        Map<String, String> aliasToTable = extractAliasToTable(sql);
        if (aliasToTable.isEmpty()) {
            return sql;
        }

        Matcher matcher = TO_TIMESTAMP_EPOCH_EXPR.matcher(sql);
        StringBuffer rewritten = new StringBuffer();
        boolean changed = false;
        while (matcher.find()) {
            String alias = matcher.group(1);
            String column = matcher.group(2);
            String table = aliasToTable.get(normalizeId(alias));
            if (table == null || table.isBlank()) {
                matcher.appendReplacement(rewritten, Matcher.quoteReplacement(matcher.group(0)));
                continue;
            }

            Optional<String> type = resolveColumnType(table, column);
            if (type.isPresent() && isTimestampLike(type.get())) {
                String replacement = alias + "." + column;
                matcher.appendReplacement(rewritten, Matcher.quoteReplacement(replacement));
                changed = true;
                continue;
            }
            matcher.appendReplacement(rewritten, Matcher.quoteReplacement(matcher.group(0)));
        }
        matcher.appendTail(rewritten);

        String out = rewritten.toString();
        if (changed) {
            log.warn("postgres.query interceptor rewrote invalid epoch conversion for timestamp/date column. original={}, rewritten={}", sql, out);
        }
        return out;
    }

    private String normalizeInvalidDateLiterals(String sql) {
        Matcher matcher = DATE_TIME_LITERAL.matcher(sql);
        StringBuffer rewritten = new StringBuffer();
        boolean changed = false;
        while (matcher.find()) {
            int year = parseInt(matcher.group(1));
            int month = parseInt(matcher.group(2));
            int day = parseInt(matcher.group(3));
            if (year > 0 && month == 2 && day == 29 && !Year.isLeap(year)) {
                String suffix = matcher.group(4) == null ? "" : matcher.group(4);
                String replacement = "'" + String.format(Locale.ROOT, "%04d-03-01", year) + suffix + "'";
                matcher.appendReplacement(rewritten, Matcher.quoteReplacement(replacement));
                changed = true;
                continue;
            }
            matcher.appendReplacement(rewritten, Matcher.quoteReplacement(matcher.group(0)));
        }
        matcher.appendTail(rewritten);
        return changed ? rewritten.toString() : sql;
    }

    private int parseInt(String value) {
        try {
            return Integer.parseInt(value);
        } catch (Exception ignore) {
            return -1;
        }
    }

    private Map<String, String> extractAliasToTable(String sql) {
        Matcher matcher = FROM_JOIN_ALIAS.matcher(sql);
        Map<String, String> out = new LinkedHashMap<>();
        while (matcher.find()) {
            String table = stripQuotes(matcher.group(1));
            String alias = stripQuotes(matcher.group(2));
            if (!table.isBlank() && !alias.isBlank()) {
                out.put(normalizeId(alias), normalizeTable(table));
            }
        }
        return out;
    }

    private Optional<String> resolveColumnType(String table, String column) {
        String tableName = normalizeTable(table);
        String colName = normalizeId(column);
        String sql = """
                SELECT c.data_type
                FROM information_schema.columns c
                WHERE c.table_name = :tableName
                  AND c.column_name = :columnName
                  AND c.table_schema = ANY (current_schemas(true))
                ORDER BY CASE WHEN c.table_schema = current_schema() THEN 0 ELSE 1 END, c.table_schema
                LIMIT 1
                """;
        Map<String, Object> params = Map.of("tableName", tableName, "columnName", colName);
        List<String> rows = jdbcTemplate.query(sql, params, (rs, rowNum) -> rs.getString(1));
        if (rows.isEmpty()) {
            return Optional.empty();
        }
        return Optional.ofNullable(rows.get(0)).map(v -> v.toLowerCase(Locale.ROOT));
    }

    private boolean isTimestampLike(String type) {
        return type.contains("timestamp") || "date".equals(type);
    }

    private String normalizeTable(String table) {
        String raw = stripQuotes(table).trim();
        int dot = raw.lastIndexOf('.');
        if (dot >= 0 && dot + 1 < raw.length()) {
            raw = raw.substring(dot + 1);
        }
        return normalizeId(raw);
    }

    private String normalizeId(String value) {
        return stripQuotes(value).trim().toLowerCase(Locale.ROOT);
    }

    private String stripQuotes(String value) {
        if (value == null) {
            return "";
        }
        String v = value.trim();
        if (v.length() >= 2 && ((v.startsWith("\"") && v.endsWith("\"")) || (v.startsWith("`") && v.endsWith("`")))) {
            return v.substring(1, v.length() - 1);
        }
        return v;
    }
}
